id: P010627
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W21759
  title: ཙནྡྲ་བྱཱ་ཀ་ར་ནའི་ཨུ་ཎའི་འགྲེལ་པ
  author: ''
  volumes:
    d0d15a3e9b5d40cc876d647fac7bc9d1:
      image_group_id: I1CZ1000
      title: ''
      volume_number: 1
      total_pages: 72
      base_file: v001.txt
